version: "3"

services:
  website:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      - INSTANCE_PRIVATE_IP=${INSTANCE_PRIVATE_IP}
      - INSTANCE_PUBLIC_IP=${INSTANCE_PUBLIC_IP}
